### ISSUE TITLE
Collect list of plugins

### ISSUE THREAD

**Issue by timurvafin** [fs/atom-bootstrap#1]
Please suggest here plugins to include in to default config

**Comment by slavakisel** [comment]
[linter-coffeelint](https://atom.io/packages/linter-coffeelint)
[pigments](https://atom.io/packages/pigments) - A package to display colors in project and files.
[ruby-block](https://atom.io/packages/ruby-block) - highlight matching ruby block
[project-manager](https://atom.io/packages/project-manager) - for easy access and switching between projects in Atom
[rspec](https://atom.io/packages/rspec) - rspec runner. Config example:

```
'rspec':
  'command': 'bin/rspec'
```

**Comment by yeremeyev** [comment]
### Syntax

atom-handlebars
atom-jade
language-slim

### Linters

linter
linter-csslint
linter-eslint
linter-jscs
linter-jshint
linter-scss-lint

### Productivity

color-picker - opens native OS colorpicker by hotkey (useful for CSS)
emmet - just emmet :smile: 
toggle-quotes - toggle between single and double quotes by CMD+SHIFT+"
atom-beautify - code formatting for lots of languages
merge-conflicts - visually resolve merge conflicts

### Look and feel

file-icons
minimap
